export const GET_POSTS = "GET_POSTS"
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS"
export const GET_POSTS_ERROR = "GET_POSTS_ERROR"

export const POST_POSTS = "POST_POSTS"
export const POST_POSTS_SUCCESS = "POST_POSTS_SUCCESS"
export const POST_POSTS_ERROR = "POST_POSTS_ERROR"